type Option = { name: string; value: string };

export const options: Option[] = [
  { name: "Alien Black Diamond 16", value: "ABD16" },
  { name: "Alpha Gut 2000 16", value: "AG200016" },
  { name: "Ashaway Dynamite 17", value: "ADYNA" },
  { name: "Ashaway Dynamite Soft 18", value: "D18SOFT" },
  { name: "Ashaway Liberty 16", value: "ASHLIB" },
  { name: "Ashaway MonoGut 16L", value: "MONOGUT16" },
  { name: "Ashaway MonoGut 17", value: "MONOGUT17" },
  { name: "Ashaway MonoGut ZX 16", value: "ZYEXMONO16" },
  { name: "Ashaway Synthetic Gut 16", value: "ASH16" },
  { name: "Babolat Addiction 16", value: "BADD16" },
  { name: "Babolat Addiction 17", value: "BADD17" },
  { name: "Babolat M7 16 (1.30)", value: "BM716G" },
  { name: "Babolat Origin 16 (1.30)", value: "BSORI16" },
  { name: "Babolat Origin 17", value: "BORIG17" },
  { name: "Babolat Pro Hurricane 16", value: "BH16" },
  { name: "Babolat Pro Hurricane 17", value: "BH17" },
  { name: "Babolat Pro Hurricane 18", value: "BH18" },
  { name: "Babolat Pro Hurricane Tour 16", value: "BH16T" },
  { name: "Babolat Pro Hurricane Tour 17", value: "BH17T" },
  { name: "Babolat RPM Blast 15L (1.35)", value: "BRPMB15" },
  { name: "Babolat RPM Blast 16", value: "BRPMB16" },
  { name: "Babolat RPM Blast 17/1.25", value: "BRPMB17" },
  { name: "Babolat RPM Blast 18 (1.20)", value: "BRPMB18" },
  { name: "Babolat RPM Blast Orange 16 (1.30)", value: "BRPMB03" },
  { name: "Babolat RPM Blast Rough 15L", value: "BRPMBR5" },
  { name: "Babolat RPM Blast Rough 16", value: "BRPMBR3" },
  { name: "Babolat RPM Blast Rough 17", value: "BRPMBRS" },
  { name: "Babolat RPM Soft 16 (1.30)", value: "RPMSF16" },
  { name: "Babolat RPM Team 16 Black", value: "BRPMT16" },
  { name: "Babolat RPM Team 17 (1.25)", value: "BRPM17" },
  { name: "Babolat SG SpiralTek 16", value: "BST16" },
  { name: "Babolat SpiralTek 17", value: "BST17" },
  { name: "Babolat Synthetic Gut 16 (1.30)", value: "BSG16" },
  { name: "Babolat Synthetic Gut 17 (1.25)", value: "BSG17" },
  { name: "Babolat Tonic + Natural Gut 16", value: "BTGUT16" },
  { name: "Babolat VS Natural Team Gut 17 (1.25)", value: "BTG17" },
  { name: "Babolat VS Natural ThermoGut 16 Touch", value: "BNG16" },
  { name: "Babolat VS Touch 15L (1.35)", value: "BNG15L" },
  { name: "Babolat Xalt 16 (1.30)", value: "BAXAL16" },
  { name: "Babolat Xcel 16", value: "NBXCEL16" },
  { name: "Babolat Xcel French Open Black 16", value: "BXCELRG" },
  { name: "Babolat Xcel French Open Black 17", value: "BXCELRG17" },
  { name: "Babolat Xcel Premium 17", value: "NBXCEL17" },
  { name: "Boris Becker Bomber 16", value: "BBB16" },
  { name: "Boris Becker Bomber 17", value: "BBB17" },
  { name: "Boris Becker Bomber NYC 16 (1.28)", value: "BBBNYC16" },
  { name: "Boris Becker Bomber NYC 17 (1.23)", value: "BBBNYC17" },
  { name: "Boris Becker Pulse 16 (1.32)", value: "BBP16" },
  { name: "Bow Brand Professional 16", value: "BBPRO16" },
  { name: "Diadem Elite XT 16", value: "DEXT16" },
  { name: "Diadem Elite XT 17", value: "DEXT17" },
  { name: "Diadem Impulse 16 (1.32)", value: "DIMP16" },
  { name: "Diadem Impulse 17 (1.25)", value: "DIMP17" },
  { name: "Diadem Solstice Blace 17 (1.20)", value: "DIASOLB" },
  { name: "Diadem Solstice Power 15L (1.35)", value: "DSP15L" },
  { name: "Diadem Solstice Power 16 (1.30)", value: "DSP16" },
  { name: "Diadem Solstice Power 16L (1.25)", value: "DSP16" },
  { name: "Diadem Solstice Power 17 (1.20)", value: "DSP17" },
  { name: "Diadem Solstice Pro 15L (1.35)", value: "DSPRO15L" },
  { name: "Diadem Solstice Pro 16L (1.25)", value: "DSPRO16L" },
  { name: "Double AR 666 (1.30)", value: "DAR666" },
  { name: "Double AR Diablo (1.24)", value: "DARD24" },
  { name: "Double AR Diablo (1.31)", value: "DARD31" },
  { name: "Double AR Raptor 1.27", value: "DARR27" },
  { name: "Double AR Twice Dragon(1.30)", value: "DARTDR" },
  { name: "Double AR Twice Shark (1.25)", value: "DARTSH" },
  { name: "Double AR WTS 25 (1.25)", value: "DARWTS25" },
  { name: "Dunlop Black Widow 16", value: "DBW16" },
  { name: "Dunlop Black Widow 17", value: "DBW17" },
  { name: "Dunlop Black Widow 18 (1.21)", value: "DBW18" },
  { name: "Dunlop Explosive 16", value: "DXP16" },
  { name: "Dunlop Explosive 17 (1.26)", value: "DES17" },
  { name: "Dunlop Explosive 18 (1.20)", value: "DXP18" },
  { name: "Dunlop Explosive Bite 17 (1.27)", value: "DEXBT17" },
  { name: "Dunlop Explosive Speed 17 (1.25)", value: "DEXSP17" },
  { name: "Dunlop Explosive Tour 16 (1.30)", value: "DXPT16" },
  { name: "Dunlop Hexy Fiber 16", value: "DHF16" },
  { name: "Dunlop Hexy Fiber 17", value: "DHF17" },
  { name: "Dunlop Ice 16 (1.30)", value: "DICE16" },
  { name: "Dunlop Ice 17 (1.25)", value: "DICE17" },
  { name: "Dunlop Iconic All 17 (1.25)", value: "DICA17" },
  { name: "Dunlop Iconic Speed 17 (1.25)", value: "DICS17" },
  { name: "Dunlop Iconic Touch 17 (1.25)", value: "DICT17" },
  { name: "Dunlop Pearl 16 (1.30)", value: "DP16" },
  { name: "Dunlop Pearl 17 (1.25)", value: "DP17" },
  { name: "Dunlop S-Gut 16 (1.32)", value: "DSG16" },
  { name: "Dunlop S-Gut 17", value: "DSG17" },
  { name: "Dunlop S-Gut 18 (1.19)", value: "DSG18W" },
  { name: "Dunlop Silk 16 (1.30)", value: "DSS16" },
  { name: "Dunlop Silk 17", value: "DSS17" },
  { name: "Forten Sweet 16", value: "F16" },
  { name: "Gamma FXT 16 (1.30)", value: "GFTX16" },
  { name: "Gamma FXT 17 (1.24)", value: "GFTX17" },
  { name: "Gamma Glide Cross String 16", value: "GGX" },
  { name: "Gamma IO 17 (1.23)", value: "GIO17" },
  { name: "Gamma IO 18 (1.18)", value: "GIO18" },
  { name: "Gamma IO Soft 15L (1.40)", value: "GIO16S15L" },
  { name: "Gamma IO Soft 16 (1.28)", value: "GIO16" },
  { name: "Gamma IO Soft 17 (1.23)", value: "GIO16S17" },
  { name: "Gamma Jet 16L (1.28)", value: "GAMJETS" },
  { name: "Gamma Live Wire 16", value: "GLW16" },
  { name: "Gamma Live Wire 17 (1.27)", value: "GLXP17" },
  { name: "Gamma Live Wire XP 16", value: "GLWXP16" },
  { name: "Gamma Live Wire XP 17 (1.27)", value: "GLXP17" },
  { name: "Gamma Marathon DPC 15 (1.40)", value: "GMDPC15" },
  { name: "Gamma Marathon DPC 16 (1.32)", value: "GMDPC16" },
  { name: "Gamma Moto 16", value: "GMOTO16" },
  { name: "Gamma Moto 17 (1.24)", value: "GMOTO17" },
  { name: "Gamma Moto Soft 16 (1.29)", value: "GMOTOS16" },
  { name: "Gamma Moto Soft 17 (1.24)", value: "GMOTOS17" },
  { name: "Gamma Ocho 16 (1.30)", value: "GO16" },
  { name: "Gamma Ocho 17 (1.25)", value: "GO17" },
  { name: "Gamma Ocho TNT 16 (1.30)", value: "GOTNT16" },
  { name: "Gamma Ocho TNT 17 (1.25)", value: "GOTNT17" },
  { name: "Gamma Ocho XP 16 (1.32)", value: "GOXP16" },
  { name: "Gamma Ocho XP 17 (1.27)", value: "GOXP17" },
  { name: "Gamma Poly Z 16", value: "GZPZ" },
  { name: "Gamma Prodigy 16", value: "GPROD16" },
  { name: "Gamma Professional 16", value: "GLWPRO16" },
  { name: "Gamma Professional 17", value: "GLWPRO17" },
  { name: "Gamma Professional 18 (1.22)", value: "GLWPRO18" },
  { name: "Gamma Professional Spin 16", value: "GLWPROS16" },
  { name: "Gamma Revelation 16", value: "GREV16" },
  { name: "Gamma Revelation 17 (1.27)", value: "GREV17" },
  { name: "Gamma RZR Rx 16", value: "GRRXBK" },
  { name: "Gamma RZR Rx 17", value: "GRRXBK17" },
  { name: "Gamma Solace 16 (1.32)", value: "GSOL16" },
  { name: "Gamma Solace 17 (1.27)", value: "GSOL17" },
  { name: "Gamma Synthetic Gut 16", value: "G16" },
  { name: "Gamma Synthetic Gut 17 (1.25)", value: "G17" },
  { name: "Gamma Synthetic Gut 17 W/wearguard (1.22)", value: "GWG17" },
  { name: "Gamma Synthetic Gut 18 (1.18)", value: "G18" },
  { name: "Gamma Synthtic Gut 15L W/wearguard (1.38)", value: "GWG15L" },
  { name: "Gamma TNT2 15L (1.40)", value: "TNT15L" },
  { name: "Gamma TNT2 16", value: "TNT16" },
  { name: "Gamma TNT2 17 (1.27)", value: "TNT17" },
  { name: "Gamma TNT2 18 (1.17)", value: "TNT218" },
  { name: "Gamma TNT2 Pro Plus 17L (1.24)", value: "TNTPP17" },
  { name: "Gamma TNT2 Rx 16", value: "TNTRX" },
  { name: "Gamma TNT2 Rx 17 (1.25)", value: "TNTRX17" },
  { name: "Gamma TNT2 Touch 16", value: "TNT2T16" },
  { name: "Gamma TNT2 Touch 17 (1.27)", value: "TNT2T17" },
  { name: "Gamma TNT2 Tour 16 (1.32)", value: "TNTT16" },
  { name: "Gamma TNT2 Tour 17 (1.27)", value: "TNTT17" },
  { name: "Gamma WearGuard Synthetic Gut 16", value: "GWG16" },
  { name: "Gamma Zo Dart 17 (1.25)", value: "GZDART17BK" },
  { name: "Gamma Zo Twist 16", value: "GZOT16NA" },
  { name: "Gamma Zo Verve 16 (1.32)", value: "GZOV16" },
  { name: "Gamma Zo Verve 17", value: "GZOV17" },
  { name: "Genesis Black Magic 16 (1.29)", value: "BM129S" },
  { name: "Gosen A.K. Control 16", value: "GAKC16" },
  { name: "Gosen AK Control 17 (1.24)", value: "GAKC17" },
  { name: "Gosen AK Pro 16", value: "STAK16" },
  { name: "Gosen AK Pro 17", value: "STAKP17" },
  { name: "Gosen AK Pro CX 16 (1.30)", value: "GAKPCX16" },
  { name: "Gosen AK Pro CX 17 (1.24)", value: "GAKPCX17" },
  { name: "Gosen AK Pro Spin 15L (1.38)", value: "GAKPS15L" },
  { name: "Gosen G-Tour 16 (1.30)", value: "GTR16BK" },
  { name: "Gosen Lumina Spin 16L (1.26)", value: "GLUM16L" },
  { name: "Gosen Multi CX 16 (1.30)", value: "GMCX16" },
  { name: "Gosen Multi CX 17 (1.24)", value: "GMCX17" },
  { name: "Gosen Nanocubic 16", value: "NANOCUB16" },
  { name: "Gosen Nanosilver 17", value: "NANOSLVR17" },
  { name: "Gosen OG Sheep Micro 17", value: "OGSW17" },
  { name: "Gosen OG Sheep Micro 18", value: "OGSM18" },
  { name: "Gosen OG Sheep Micro Super 16L", value: "OGMS16L" },
  { name: "Gosen OG-Sheep Micro 16", value: "OGS16" },
  { name: "Gosen Poly Professional 16 (1.29)", value: "GPP16W" },
  { name: "Gosen Poly Professional 17 (1.24)", value: "GPP17W" },
  { name: "Gosen Polylon 17 (1.24)", value: "GPLY17" },
  { name: "Gosen Polylon PolyBreak 17 (1.24)", value: "POLYBRK17" },
  { name: "Gosen Polylon PolyBreak 18 (1.20)", value: "POLYBRK18" },
  { name: "Gosen Polylon Premium 16 (1.32)", value: "PPREM16" },
  { name: "Gosen Polylon Premium 16L (1.27)", value: "PPREM16L" },
  { name: "Gosen Sidewinder 16 (1.31)", value: "GSW16" },
  { name: "Gosen Sidewinder 17", value: "GSW17BK" },
  { name: "Gosen Tecflex 16 (1.30)", value: "GTF16" },
  { name: "Gosen TecGut Remplir 16", value: "GTGREMP16" },
  { name: "Grapplesnake Alpha 17 (1.25)", value: "GALP125" },
  { name: "Grapplesnake Tour M8 17 (1.25)", value: "GM8S7" },
  { name: "Grapplesnake Tour Sniper 1.25", value: "GTSS125" },
  { name: "Head C3 Rocket 16", value: "HC316W" },
  { name: "Head FXP Power 16", value: "HFXPP16" },
  { name: "Head FXP Power 17", value: "HFXPP17" },
  { name: "Head FXP Tour 16", value: "HFXPT16" },
  { name: "Head Hawk 16 (1.30)", value: "HAWK16" },
  { name: "Head Hawk 17 (1.25)", value: "HAWK17" },
  { name: "Head Hawk 18 (1.20)", value: "HAWK18" },
  { name: "Head Hawk Power 17 (1.25)", value: "HAWKP17" },
  { name: "Head Hawk Rough 17", value: "HHR" },
  { name: "Head Hawk Touch 18 (1.20)", value: "HWAKT18" },
  { name: "Head Hawk Touch 19 (1.15)", value: "HWAKT19" },
  { name: "Head Lynx 16 (1.30)", value: "LYNX16" },
  { name: "Head Lynx 17 (1.25)", value: "LYNX17" },
  { name: "Head Lynx 18 (1.20)", value: "LYNX18" },
  { name: "Head Lynx Touch 16g (1.30)", value: "LYNXT16" },
  { name: "Head Lynx Tour 16 (1.30)", value: "LT16CH" },
  { name: "Head Lynx Tour 17 (1.25)", value: "LTR17" },
  { name: "Head Reflex MLT 16 (1.30)", value: "HRMLT16" },
  { name: "Head Reflex MLT 17 (1.25)", value: "HRMLT17" },
  { name: "Head RIP Control 16", value: "RCON16" },
  { name: "Head Rip Control 17 (1.25)", value: "RCON17" },
  { name: "Head Sonic Pro 16", value: "SONIC16" },
  { name: "Head Sonic Pro 17", value: "SONIC17" },
  { name: "Head Sonic Pro Edge 16", value: "HSPE16" },
  { name: "Head Synthetic Gut PPS 16", value: "HPPS16" },
  { name: "Head Synthetic Gut PPS 17 (1.25)", value: "HPPS17" },
  { name: "Head Velocity MLT 17 (1.25)", value: "VMLT17" },
  { name: "Head Velocity MLT Power 16 (1.30)", value: "VMLTP16" },
  { name: "IsoSpeed Axon Mono 16L", value: "ISOAX16L" },
  { name: "IsoSpeed Axon Multi 16L", value: "ISOAXMUL16L" },
  { name: "IsoSpeed Black Fire 17", value: "ISOBF16" },
  { name: "IsoSpeed Control 16", value: "ISOC16" },
  { name: "IsoSpeed Control Classic 16", value: "ISOCC16" },
  { name: "IsoSpeed Cream 17 (1.28)", value: "ISOCREAM16" },
  { name: "IsoSpeed Energetic 17", value: "ISOEN17" },
  { name: "IsoSpeed Energetic Plus 16", value: "ISOENP" },
  { name: "IsoSpeed Professional Classic 17", value: "ISOPC17" },
  { name: "IsoSpeed Pulse 16", value: "ISOPUL16" },
  { name: "IsoSpeed Pulse 17", value: "ISOPUL17" },
  { name: "IsoSpeed Pyramid 16", value: "ISOP16" },
  { name: "IsoSpeed V18 19 (1.12)", value: "ISOTPV18" },
  { name: "Kirschbaum Black Shark 16 (1.30)", value: "SHARK16BK" },
  { name: "Kirschbaum Competition 16/1.30", value: "COMPK130" },
  { name: "Kirschbaum Competition 17 (1.25)", value: "COMPK125" },
  { name: "Kirschbaum Competition 17L (1.20)", value: "COMPK17" },
  { name: "Kirschbaum Flash 16 (1.30)", value: "KFLASH" },
  { name: "Kirschbaum Max Power 16 (1.30)", value: "KMAXPWR16" },
  { name: "Kirschbaum Max Power 17 (1.25)", value: "KMAXPWR17" },
  { name: "Kirschbaum Max Power 18 (1.20)", value: "KMAXPWR18" },
  { name: "Kirschbaum Max Power Rough 16 (1.30)", value: "KMAXPWRR16" },
  { name: "Kirschbaum Max Power Rough 17 (1.25)", value: "KMAXPWRR17" },
  { name: "Kirschbaum Max Power Rough 18 (1.20)", value: "KMAXPWRR18" },
  { name: "Kirschbaum Pro Line Evolution 17 (1.25)", value: "PLE2125BLU" },
  { name: "Kirschbaum Pro Line II 1.30", value: "PL2130" },
  { name: "Kirschbaum Pro Line II 17 (1.25)", value: "PL2125BK" },
  { name: "Kirschbaum Pro Line II 17L (1.20)", value: "PL2120BK" },
  { name: "Kirschbaum Pro Line II 18 (1.15)", value: "PL2115" },
  { name: "Kirschbaum Pro Line X 16 (1.30)", value: "PLX16CO" },
  { name: "Kirschbaum Pro Line X 17 (1.25)", value: "PLX17CO" },
  { name: "Kirschbaum Spiky Shark 16", value: "SHARK16" },
  { name: "Kirschbaum Spiky Shark 17", value: "SHARK17" },
  { name: "Kirschbaum Super Smash 16/1.30", value: "SMASH16" },
  { name: "Kirschbaum Super Smash 17 (1.25)", value: "SMSH17120" },
  { name: "Kirschbaum Touch Multifibre 16", value: "TMULTI16" },
  { name: "Kirschbaum Touch Multifibre 17 (1.25)", value: "TMULTI17" },
  { name: "Kirschbaum Xplosive Speed 1.25", value: "XS17" },
  { name: "Kirschbaum Xplosive Speed 1.30", value: "XS16" },
  { name: "Klip Hardcore 16/1.30", value: "KHC16" },
  { name: "Klip K-Boom 18 (1.20)", value: "KB00M18" },
  { name: "Klip Kicker 16", value: "KICK16" },
  { name: "Klip Legend 16 Uncoated", value: "KLIPLUC16" },
  { name: "Klip Legend 17 (1.25)", value: "KLNG17" },
  { name: "Klip Scorcher 17 (1.27)", value: "KSCOR17" },
  { name: "LaserFibre 1200 16 (1.30)", value: "LL1216" },
  { name: "LaserFibre JB Tour 100 17g (1.25)", value: "LJBT10017" },
  { name: "LaserFibre Native Tour 17 (1.25)", value: "LNT17" },
  { name: "LaserFibre Supreme 2.0 16 (1.30)", value: "LS216" },
  { name: "LaserFibre Supreme 2.0 17 (1.25)", value: "LS217" },
  { name: "LaserFibre Vorso 16 (1.28)", value: "LV16" },
  { name: "LaserFibre Vorso 17 (1.23)", value: "LV17" },
  { name: "Luxilon 4G 16 (1.30)", value: "LUX4G130" },
  { name: "Luxilon 4G 16L (1.25)", value: "LUX4G125" },
  { name: "Luxilon 4G Rough 16L", value: "LUX4GR125" },
  { name: "Luxilon 4G S 15", value: "LUX4GS141" },
  { name: "Luxilon 4G Soft 1.25", value: "LUX4GS16" },
  { name: "Luxilon Adrenaline 16", value: "LADR120" },
  { name: "Luxilon Adrenaline 16L/1.25", value: "LADR125" },
  { name: "Luxilon Adrenaline Rough 16L/1.25", value: "LA125" },
  { name: "Luxilon ALU Power 125/16L", value: "ALUSTR" },
  { name: "Luxilon ALU Power Feel 18/1.20", value: "ALUPF16" },
  { name: "Luxilon ALU Power Rough 16L (1.25)", value: "ALUPR16" },
  { name: "Luxilon Alu Power Soft 1.25", value: "ALUPRSFT16" },
  { name: "Luxilon Alu Power Vibe 16 (1.25)", value: "LALUPV" },
  { name: "Luxilon Big Banger Ace 18 (1.12)", value: "BBACE18" },
  { name: "Luxilon Big Banger ALU Power Fluoro 17", value: "BALUFL" },
  { name: "Luxilon Big Banger ALU Power Spin 127/16", value: "ALUPRSPIN" },
  { name: "Luxilon Big Banger Original 130/16", value: "BB16" },
  { name: "Luxilon Big Banger Rough 130/16", value: "BBR16" },
  { name: "Luxilon Big Banger TiMO 17L (1.17)", value: "TBS17L" },
  { name: "Luxilon ECO Power 17 (1.25)", value: "LAECOPS" },
  { name: "Luxilon ECO Spin 17 (1.25)", value: "LXNECS" },
  { name: "Luxilon Element 1.30", value: "LE130" },
  { name: "Luxilon Element 16L (1.25)", value: "LE125" },
  { name: "Luxilon Element Rough 16 (1.30)", value: "LER130" },
  { name: "Luxilon Element Soft IR 1.27", value: "LEIR27S" },
  { name: "Luxilon LXN Smart 16 (1.30)", value: "LUS16S" },
  { name: "Luxilon LXN Smart 16L (1.25)", value: "LUS16LS" },
  { name: "Luxilon M2 Plus 130/16", value: "LM2PLUS16" },
  { name: "Luxilon M2 Pro 125/16", value: "LM2PRO16L" },
  { name: "Luxilon Natural Gut 1.25", value: "LNAT16L" },
  { name: "Luxilon Savage 16/1.27", value: "LUXSAV" },
  { name: "MSV Co-Focus 17L (1.18)", value: "MSVCF17" },
  { name: "MSV Co.-Focus 16L", value: "MSVCF16" },
  { name: "MSV Focus Evo 16", value: "FEVO16" },
  { name: "MSV Focus Evo 17", value: "FEVO17" },
  { name: "MSV Focus Hex 17L (1.18)", value: "MSVFH" },
  { name: "MSV Focus Hex Soft  17 (1.25)", value: "FHS16RD" },
  { name: "MSV Focus Hex Soft 17L (1.20)", value: "FHS17YE" },
  { name: "MSV Focus-Hex +38 16L (1.25)", value: "FH38125BK" },
  { name: "MSV Focus-Hex 16 (1.23)", value: "MSVFH16R" },
  { name: "MSV Focus-Hex 16 (1.27)", value: "MSVFH16" },
  { name: "MSV Hepta-Twist 16", value: "HEPTW16WH" },
  { name: "MSV Hepta-Twist 17", value: "HEPTW17WH" },
  { name: "One Strings Carbon Tour 17 (1.25)", value: "OSCT17S" },
  { name: "Pacific Classic Natural Gut 16", value: "PNGC16" },
  { name: "Pacific PMX 16L", value: "PPMX16" },
  { name: "Pacific PMX 17", value: "PPMX17" },
  { name: "Pacific Poly Force 16L", value: "PPFO16" },
  { name: "Pacific Poly Force 17", value: "PPFO17" },
  { name: "Pacific Poly Power Pro 16 (1.30)", value: "PPPRO130" },
  { name: "Pacific Poly Power Pro 16L (1.25)", value: "PPPP16" },
  { name: "Pacific Premium Power X 16L", value: "PPX16" },
  { name: "Pacific Prime Gut Orange Bull 16 (1.30)", value: "PPGOB16" },
  { name: "Pacific Prime Gut Orange Bull 16L (1.25)", value: "PPGOB16L" },
  { name: "Pacific Prime Natural Gut 16", value: "PNGP16" },
  { name: "Pacific Prime Natural Gut 16L", value: "PNGP16L" },
  { name: "Pacific Tough Gut 16", value: "PTG16" },
  { name: "Pacific Tough Gut 16L", value: "PTG16L" },
  { name: "Pacific X Force 16L (1.29)", value: "PXF16L" },
  { name: "Pacific X Force 17", value: "PXF17" },
  { name: "Pacific X Force 18", value: "PXF18" },
  { name: "Pacific XCite 16 (1.30)", value: "PXC160" },
  { name: "Pacific XCite 16L (1.25)", value: "PXC16L" },
  { name: "Polyfibre Black Venom 16 (1.30)", value: "PFBV16S" },
  { name: "Polyfibre Black Venom 16L (1.25)", value: "PFBV17S" },
  { name: "Polyfibre Black Venom Rough 16L (1.25)", value: "PFBVR17S" },
  { name: "Polyfibre Cobra 17/1.20", value: "PFRAZ17" },
  { name: "Polyfibre Hexablade 16L (1.25)", value: "PFHB16S" },
  { name: "Polyfibre Hexablade 17L (1.18)", value: "PFHB17S" },
  { name: "Polyfibre Hightec Premium 16/1.30", value: "HTP160" },
  { name: "Polyfibre Hightec Premium 16L", value: "HTP16L" },
  { name: "Polyfibre Hightec Premium 17", value: "HTP17" },
  { name: "Polyfibre Panthera 16 (1.30)", value: "PANTH16" },
  { name: "Polyfibre Poly Hightec 16/1.30", value: "PHT16" },
  { name: "Polyfibre Poly Hightec 16L", value: "PHT16L" },
  { name: "Polyfibre Poly Hightec 17", value: "PHT17" },
  { name: "Polyfibre Poly Hightec 18", value: "PHT18" },
  { name: "Polyfibre TCS 16/1.30", value: "TCS16" },
  { name: "Polyfibre TCS 16L", value: "TCS16L" },
  { name: "Polyfibre TCS 17", value: "TCS17" },
  { name: "Polyfibre TCS Rapid 16L/1.25", value: "TCSR16L" },
  { name: "Polyfibre Viper 16L/1.25", value: "VIPER16L" },
  { name: "Polyfibre Viper 17/1.20", value: "VIPER17" },
  { name: "Prince Beast XP 16", value: "PB16" },
  { name: "Prince Diablo Prism 17", value: "PDPRSM17B" },
  { name: "Prince Lightning Pro 16 (1.30)", value: "PLPRO16" },
  { name: "Prince Lightning XX 16", value: "PLXX16" },
  { name: "Prince Lightning XX 17", value: "PLXX17" },
  { name: "Prince Perfection 16 (1.30)", value: "GPER16" },
  { name: "Prince Premier Control 15L", value: "PPC15L" },
  { name: "Prince Premier Control 16", value: "PPC16" },
  { name: "Prince Premier Control 17", value: "PPC17" },
  { name: "Prince Premier Power 16", value: "PPPWR16" },
  { name: "Prince Premier Power 17", value: "PPPWR17" },
  { name: "Prince Premier Touch 16", value: "PPT16" },
  { name: "Prince Premier Touch 17", value: "PPT17" },
  { name: "Prince Syn Gut Original 16", value: "OS16" },
  { name: "Prince Syn Gut Original 17", value: "OS17" },
  { name: "Prince Synthetic Gut 16 Duraflex", value: "S16" },
  { name: "Prince Synthetic Gut 17 Duraflex", value: "S17" },
  { name: "Prince Topspin W/ Duraflex 15L", value: "T15" },
  { name: "Prince Tour XC 15L", value: "PTXC15L" },
  { name: "Prince Tour XC 16L", value: "PTXC16L" },
  { name: "Prince Tour XC 17L", value: "PTXC17L" },
  { name: "Prince Tour XP 15L", value: "PTXP15L" },
  { name: "Prince Tour XP 16", value: "PTXP16" },
  { name: "Prince Tour XP 17 (1.25)", value: "PTXP17" },
  { name: "Prince Tour XR 15L (1.35)", value: "PTXR15L" },
  { name: "Prince Tour XR 16 (1.30)", value: "PTXR16" },
  { name: "Prince Tour XR 17 (1.25)", value: "PTXR17" },
  { name: "Prince Tour XS 1.35", value: "PTXS135" },
  { name: "Prince Tour XS 16", value: "PTXS125" },
  { name: "Prince Tour XT 18", value: "PTXT18" },
  { name: "Prince Tournament Nylon 15L", value: "PN" },
  { name: "Prince Vortex 16 (1.30)", value: "PVRTX16" },
  { name: "RS RS Lyon 17", value: "RSL17" },
  { name: "RS RS Lyon 17L (1.20)", value: "RSL17L" },
  { name: "Signum Pro Firestorm 1.25", value: "SFS17" },
  { name: "Signum Pro Firestorm 16 (1.30)", value: "SFS16" },
  { name: "Signum Pro Hyperion 16", value: "SIGHYP160" },
  { name: "Signum Pro Hyperion 17 (1.24)", value: "SIGHYP170" },
  { name: "Signum Pro Hyperion 18 (1.18)", value: "SIGHYP180" },
  { name: "Signum Pro Plasma HEXtreme 16 (1.30)", value: "SIGPHEX16" },
  { name: "Signum Pro Plasma HEXtreme 16L/1.25", value: "SIGPHEX16" },
  { name: "Signum Pro Poly Megaforce 16", value: "SIGPPM16" },
  { name: "Signum Pro Poly Megaforce 17 (1.19)", value: "SIGPPM17L" },
  { name: "Signum Pro Poly Plasma 17 (1.23)", value: "SIGPPP170" },
  { name: "Signum Pro Poly Speed Spin 1.28", value: "SIGPSS16" },
  { name: "Signum Pro Poly-Plasma 16L", value: "SIGPPP16L" },
  { name: "Signum Pro Poly-Plasma 17L (1.18)", value: "SIGPPP17L" },
  { name: "Signum Pro Poly-Plasma Pure 16L", value: "SIGPPP16LW" },
  { name: "Signum Pro Poly-Plasma Pure 17 (1.23)", value: "SIGPPP170W" },
  { name: "Signum Pro Poly-Plasma Pure 17L (1.18)", value: "SIGPPP17LW" },
  { name: "Signum Pro Tornado 16", value: "SIGTORN160" },
  { name: "Signum Pro Tornado 17 (1.23)", value: "SIGTORN170" },
  { name: "Signum Pro Tornado 18 (1.17)", value: "SIGTORN180" },
  { name: "Signum Pro X-Perience 17 (1.24)", value: "SIGX17" },
  { name: "Signum Pro Yellow Jacket 17g (1.22)", value: "SPYJ17" },
  { name: "Solinco Barb Wire 16", value: "SBW16" },
  { name: "Solinco Barb Wire 16L (1.25)", value: "SBW16L" },
  { name: "Solinco Barb Wire 17 (1.20)", value: "SBW17" },
  { name: "Solinco Confidential 16 (1.30)", value: "SLNC16LS" },
  { name: "Solinco Hyper-G 16", value: "SHG16" },
  { name: "Solinco Hyper-G 16L (1.25)", value: "SHG16L" },
  { name: "Solinco Hyper-G 17 (1.20)", value: "SHG17" },
  { name: "Solinco Hyper-G 18 (1.15)", value: "SHG18" },
  { name: "Solinco Hyper-G-Soft 16L (1.25)", value: "SHGS16L" },
  { name: "Solinco Mach 10 16 (1.30)", value: "SM10130" },
  { name: "Solinco Outlast 16", value: "SOUT16" },
  { name: "Solinco Outlast 16L (1.25)", value: "SOUT16L" },
  { name: "Solinco Outlast 17", value: "SOUT17" },
  { name: "Solinco Outlast 18 (1.15)", value: "SOUT18" },
  { name: "Solinco Revolution 16", value: "SREV16" },
  { name: "Solinco Revolution 16L (1.25)", value: "SREV16L" },
  { name: "Solinco Revolution 17", value: "SREV17" },
  { name: "Solinco Revolution 18 (1.16)", value: "SREV18" },
  { name: "Solinco Tour Bite 15L (1.35)", value: "STB15L" },
  { name: "Solinco Tour Bite 16", value: "STB16" },
  { name: "Solinco Tour Bite 16 Soft", value: "STBS16" },
  { name: "Solinco Tour Bite 16L (1.25)", value: "STB16L" },
  { name: "Solinco Tour Bite 17", value: "STB17" },
  { name: "Solinco Tour Bite 18 (1.15)", value: "STB18" },
  { name: "Solinco Tour Bite 19 (1.10)", value: "STB19" },
  { name: "Solinco Tour Bite 20 (1.05)", value: "STB20" },
  { name: "Solinco Tour Bite Diamond Rough 16 (1.30)", value: "STBDR16" },
  { name: "Solinco Tour Bite Diamond Rough 17 (1.20)", value: "STBDR17" },
  { name: "Solinco Tour Bite Soft 16L (1.25)", value: "STBS16L" },
  { name: "Solinco Tour Bite Soft 17 (1.20)", value: "STBS17" },
  { name: "Solinco Tour Bite Soft 18 (1.15)", value: "STBS18" },
  { name: "Solinco Vanquish 16", value: "SVAN16" },
  { name: "Solinco Vanquish 17 (1.20)", value: "SVAN17" },
  { name: "Solinco X-Natural 16 (1.30)", value: "SXN16" },
  { name: "Solinco X-Natural 17 (1.20)", value: "SXN17" },
  { name: "Tecnifibre Black Code 15L (1.32)", value: "TBC15L" },
  { name: "Tecnifibre Black Code 16", value: "TBC16" },
  { name: "Tecnifibre Black Code 17", value: "TBC17" },
  { name: "Tecnifibre Black Code 18", value: "TBC18" },
  { name: "Tecnifibre Black Code 4S 16 (1.30)", value: "TBC4S16" },
  { name: "Tecnifibre Black Code 4S 17 (1.25)", value: "TBC4S17" },
  { name: "Tecnifibre Black Code 4S 18 (1.20)", value: "TBC4S18" },
  { name: "Tecnifibre Duramix HD 16", value: "TDMHD16" },
  { name: "Tecnifibre Duramix HD 17", value: "TDMHD17" },
  { name: "Tecnifibre E-Matrix 16", value: "EMX16" },
  { name: "Tecnifibre E-Matrix 17", value: "EMX17" },
  { name: "Tecnifibre HDX Tour 16 (1.30)", value: "HDXT16" },
  { name: "Tecnifibre HDX Tour 17 (1.24)", value: "HDX17" },
  { name: "Tecnifibre Ice Code 16 (1.30)", value: "TICW16" },
  { name: "Tecnifibre Multi-Feel 16", value: "MF16" },
  { name: "Tecnifibre Multi-Feel 17 (1.25)", value: "MF17" },
  { name: "Tecnifibre Multifeel 16 Black (1.30)", value: "MF16BK" },
  { name: "Tecnifibre NRG2 16", value: "NRG16" },
  { name: "Tecnifibre NRG2 17/1.24", value: "NRG17" },
  { name: "Tecnifibre NRG2 18 (1.18)", value: "NRG18" },
  { name: "Tecnifibre Pro Red Code 16", value: "TPRC16" },
  { name: "Tecnifibre Pro Red Code 17", value: "TPRC17" },
  { name: "Tecnifibre Pro Red Code 18", value: "TPRC18" },
  { name: "Tecnifibre Pro Red Code Wax 17", value: "TPRCW17" },
  { name: "Tecnifibre Razor Code 16 (1.30)", value: "TFRC16B" },
  { name: "Tecnifibre Razor Code 17 (1.25)", value: "TFRC17B" },
  { name: "Tecnifibre Razor Code 18 (1.20)", value: "TFRC18B" },
  { name: "Tecnifibre Razor Soft 17 (1.25)", value: "TRSB17" },
  { name: "Tecnifibre Ruff Code 16 (1.30)", value: "TRUC16" },
  { name: "Tecnifibre Ruff Code 17 (1.25)", value: "TRUC17" },
  { name: "Tecnifibre TGV 16", value: "TGV16" },
  { name: "Tecnifibre TGV 17/1.25", value: "TGV17" },
  { name: "Tecnifibre Triax 16 (1.33)", value: "TSTX33" },
  { name: "Tecnifibre X-One Biphase 16", value: "X116" },
  { name: "Tecnifibre X-One Biphase 17", value: "X117" },
  { name: "Tecnifibre X-One Biphase 18", value: "X118" },
  { name: "Toalson Leoina 77 (1.30)", value: "LEO77" },
  { name: "Topspin Cyber Blue 16", value: "CPOW16" },
  { name: "Topspin Cyber Blue 17", value: "CPOW17" },
  { name: "Topspin Cyber Blue 17L (1.20)", value: "CPOW17L" },
  { name: "Topspin Cyber Delta 17 (1.26)", value: "DELTA17" },
  { name: "Topspin Cyber Flash 16", value: "TCF16" },
  { name: "Topspin Cyber Flash 17", value: "TCF17" },
  { name: "Topspin Cyber Flash 17L", value: "TCF17L" },
  { name: "Topspin Cyber Whirl 17 (1.24)", value: "CW16" },
  { name: "Toroline O-Toro 17 (1.23)", value: "TOTORO7" },
  { name: "Toroline O-Toro Spin 17 (1.23)", value: "T7TOROS" },
  { name: "Toroline O-Toro Tour 17 (1.23)", value: "T7TOROT" },
  { name: "Tourna Big HItter Black 7 16 (1.25)", value: "UBHBK16" },
  { name: "Tourna Big Hitter Black 7 17", value: "UBHBK17" },
  { name: "Tourna Big Hitter Blue 16", value: "UBHB16" },
  { name: "Tourna Big Hitter Blue 17", value: "UBHB17" },
  { name: "Tourna Big Hitter Blue Rough 16", value: "UBHBR16" },
  { name: "Tourna Big Hitter Blue Rough 17", value: "UBHBR17" },
  { name: "Tourna Big HItter Silver 16", value: "UBIGHIT" },
  { name: "Tourna Big Hitter Silver 17", value: "UBIGHIT17" },
  { name: "Tourna Big Hitter Silver 7 Tour 16 (1.30)", value: "TS7TR16S" },
  { name: "Tourna Big Hitter Silver Rough 16", value: "UBHITR" },
  { name: "Tourna Big Hitter Silver Rough 17", value: "UBHIT17R" },
  { name: "Tourna Black Zone 16", value: "UBKZ16" },
  { name: "Tourna Black Zone 17", value: "UBKZ17" },
  { name: "Tourna Irradiated 16", value: "TFIBER" },
  { name: "Tourna Irradiated 17", value: "TFIBER17" },
  { name: "Tourna Quasi Gut 17", value: "TQG17" },
  { name: "Tourna Quasi-Gut 16", value: "TQG16" },
  { name: "Tourna Quasi-Gut Armor 16", value: "TQGA16" },
  { name: "Tourna Quasi-Gut Armor 17", value: "TQGA17" },
  { name: "Tourna Synthetic Gut Armor 16", value: "USGA16BK" },
  { name: "Tourna Synthetic Gut Armor 17", value: "USGA17BK" },
  { name: "Volkl Cyclone 16", value: "VCYC" },
  { name: "Volkl Cyclone 17", value: "VCYC17S" },
  { name: "Volkl Cyclone 18", value: "VCYC18S" },
  { name: "Volkl Cyclone 18L (1.15)", value: "VCYC18L" },
  { name: "Volkl Cyclone 19 (1.10)", value: "VCYC19" },
  { name: "Volkl Cyclone Tour 16 (1.30)", value: "VCTBK16" },
  { name: "Volkl Cyclone Tour 17 (1.25)", value: "VCTR17" },
  { name: "Volkl Cyclone Tour 18 (1.20)", value: "VCTBK18" },
  { name: "Volkl Power-Fiber II 16", value: "VPF16" },
  { name: "Volkl Power-Fiber II 17", value: "VPF17" },
  { name: "Volkl V-Pro 16", value: "VVPS16" },
  { name: "Volkl V-Pro 17", value: "VVPS17" },
  { name: "Volkl V-Pro 18", value: "VVPS18" },
  { name: "Volkl V-Square 16 (1.30)", value: "VSQ16" },
  { name: "Volkl V-Star 16 (1.30)", value: "VS16S" },
  { name: "Volkl V-Star 18 (1.20)", value: "VS18S" },
  { name: "Volkl V-Star 18L (1.15)", value: "VS18LSI" },
  { name: "Volkl V-Star 19 (1.10)", value: "VS19SI" },
  { name: "Volkl V-Torque 16", value: "VT16" },
  { name: "Volkl V-Torque 18 (1.18)", value: "VT18" },
  { name: "Volkl V-Torque Tour 16 (1.30)", value: "VTTW16" },
  { name: "Weiss Cannon 6 Star 16 (1.30)", value: "WCSSSS" },
  { name: "Weiss Cannon Black 5 Edge 17 (1.24)", value: "WCBFE" },
  { name: "Weiss Cannon Blue Rock N Power", value: "WBRP" },
  { name: "Weiss Cannon Explosiv 1.30", value: "WCX133" },
  { name: "Weiss Cannon MatchPower 1.25", value: "WCMP125" },
  { name: "Weiss Cannon Mosquito Bite 18 (1.16)", value: "WCMB" },
  { name: "Weiss Cannon Red Ghost  17L (1.18)", value: "WCRG17L" },
  { name: "Weiss Cannon Scorpion 1.22", value: "WCSC122" },
  { name: "Weiss Cannon Scorpion 1.33", value: "WCSC133" },
  { name: "Weiss Cannon Scorpion 16L (1.28)", value: "WCSC128" },
  { name: "Weiss Cannon Silverstring 1.25", value: "WCS125" },
  { name: "Weiss Cannon Silverstring 120", value: "WCS120" },
  { name: "Weiss Cannon Turbotwist 17 (1.24)", value: "TURBTW17" },
  { name: "Weiss Cannon Turbotwist 17L (1.18)", value: "TURBTW17L" },
  { name: "Weiss Cannon Ultra Cable 17 (1.23)", value: "WCUC17" },
  { name: "Wilson Enduro Mono 16L", value: "WENDM16L" },
  { name: "Wilson Natural Gut 16 (1.30)", value: "WNATY16" },
  { name: "Wilson Natural Gut 17", value: "WNAT17" },
  { name: "Wilson NXT 15L (1.35)", value: "WNXT15L" },
  { name: "Wilson NXT 16", value: "NXT16" },
  { name: "Wilson NXT 17", value: "NXT17" },
  { name: "Wilson NXT Control 16 (1.32)", value: "NXTC16" },
  { name: "Wilson NXT Duramax 15 (1.40)", value: "NXTDM15" },
  { name: "Wilson NXT Duramax 16 (1.32)", value: "NXTDM16" },
  { name: "Wilson NXT Max 15L (1.35)", value: "NXTM15L" },
  { name: "Wilson NXT Max 16", value: "NXTMAX16" },
  { name: "Wilson NXT Power 17 (1.26)", value: "NXTP17" },
  { name: "Wilson Optimus 16 (1.30)", value: "WOPT16" },
  { name: "Wilson Revolve 15 (1.35)", value: "WRV15" },
  { name: "Wilson Revolve 16 (1.30)", value: "WRV16" },
  { name: "Wilson Revolve 17 (1.25)", value: "WRV17" },
  { name: "Wilson Revolve Spin 16", value: "WRS16" },
  { name: "Wilson Sensation 15 (1.35)", value: "SEN15" },
  { name: "Wilson Sensation 16", value: "SEN16" },
  { name: "Wilson Sensation 17", value: "SEN17" },
  { name: "Wilson Sensation Control 16 (1.30)", value: "WSC16" },
  { name: "Wilson Synthetic Gut Control 17 (1.25)", value: "WSGC17" },
  { name: "Wilson Synthetic Gut Power 16 (1.30)", value: "WSGP16" },
  { name: "Wilson Synthetic Gut Power 17 (1.25)", value: "WSGP17" },
  { name: "Y-Tex Quadro Twist 16L", value: "YTQTBK16L" },
  { name: "Yonex Dynawire 16 (1.30)", value: "YDW16" },
  { name: "Yonex Mono Preme 16 (1.30)", value: "YMPS130" },
  { name: "Yonex Poly Tour 130/16", value: "YPT130" },
  { name: "Yonex Poly Tour Air 16L", value: "YPTA125BL" },
  { name: "Yonex Poly Tour Drive 16L (1.25)", value: "YPTD16L" },
  { name: "Yonex Poly Tour Fire 16L (1.25)", value: "YPTF125" },
  { name: "Yonex Poly Tour HS 16 (1.30)", value: "YPTP130GN" },
  { name: "Yonex Poly Tour HS 16L (1.25)", value: "YPTP125GN" },
  { name: "Yonex Poly Tour Pro 17 (1.20)", value: "YPTP120" },
  { name: "Yonex Poly Tour Pro Yellow 16 (1.30)", value: "YPTP130" },
  { name: "Yonex Poly Tour Pro Yellow 16L (1.25)", value: "YPTP125" },
  { name: "Yonex Poly Tour Spin 16L (1.25)", value: "YPTS125" },
  { name: "Yonex Poly Tour Spin G 1.25", value: "YPTSG16LR" },
  { name: "Yonex Poly Tour Strike 16L (1.25)", value: "YPTS16L" },
  { name: "Yonex Poly Tour Tough 16L", value: "YPTT125BK" },
  { name: "Yonex PolyTour REV 16 (1.30)", value: "YPTR16" },
  { name: "Yonex Polytour Rev 16L (1.25)", value: "YPTR16L" },
  { name: "Yonex Rexis 16 (1.30)", value: "YREX160" },
  { name: "Yonex Rexis Comfort 16L (1.25)", value: "YREXCL" },
  { name: "Yonex Rexis Speed 16L (1.25)", value: "YREXSL" },
  { name: "Yonex Tour Super 850 16 (1.30)", value: "ATG850" },
  { name: "Yonex Tour Super Pro 850 16 (1.32)", value: "Y85016" },
];
