import { useEffect, useRef } from "react";

import type { StringDoc } from "./Layout";
import { useAnalysis } from "./useAnalysis";

type AnalysisProps = {
  doc: StringDoc;
};

export const Analysis = ({ doc }: AnalysisProps) => {
  const hasCompleted = useRef(false);

  const { completion, isLoading, complete } = useAnalysis();

  // trigger analysis on mount
  useEffect(() => {
    if (hasCompleted.current || !doc) return;
    hasCompleted.current = true;

    complete(JSON.stringify(doc));
  }, [doc?.custom_id]);

  console.log("AI Analysis completion:", completion);

  return (
    <div className="flex flex-col gap-2 rounded-xl border border-gray-100 dark:border-gray-800 p-5">
      <div className="flex items-center gap-2 mb-3">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="text-gray-400"
        >
          <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" />
        </svg>
        <span className="text-xs font-medium uppercase tracking-wider text-gray-400">
          AI analysis
        </span>
      </div>

      {isLoading && !completion ? (
        <div className="space-y-2 animate-pulse">
          <div className="h-3 w-[95%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[88%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[92%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[60%] rounded-full bg-gray-100 dark:bg-gray-800" />

          <div className="h-3 w-[95%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[88%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[92%] rounded-full bg-gray-100 dark:bg-gray-800" />
          <div className="h-3 w-[60%] rounded-full bg-gray-100 dark:bg-gray-800" />
        </div>
      ) : (
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed text-left">
          {completion}
        </p>
      )}

      <p className="text-[11px] text-gray-300 dark:text-gray-600 mt-4 pt-3 border-t border-gray-100 dark:border-gray-800">
        Generated by AI · may not reflect current data
      </p>
    </div>
  );
};
